/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.estacao.apresentacao;

import com.mycompany.estacao.modelo.Estaticos;
import com.mycompany.estacao.modelo.Serial;
import java.util.Timer;
import java.util.TimerTask;


/**
 *
 * @author rever
 */
public class frmPrincipal extends javax.swing.JDialog
{

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        atualizarTela();
    }
    
    public void atualizarTela()
    {
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask()
        {
            @Override
            public void run()
            {
                lblUmidadeValor.setText(Estaticos.umidade + " %");
                lblTemperaturaValor.setText(Estaticos.temperatura + " ºC");
                lblPrecipitacaoValor.setText(Estaticos.precipitacao);
            }
        }, 1000, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel6 = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        lblTemperaturaValor = new javax.swing.JLabel();
        lblUmidade = new javax.swing.JLabel();
        lblUmidadeValor = new javax.swing.JLabel();
        lblPrecipitacao = new javax.swing.JLabel();
        lblPrecipitacaoValor = new javax.swing.JLabel();
        btnIniciarParar = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estação Climática");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        lblTemperatura.setText("Temperatura");

        lblTemperaturaValor.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTemperaturaValor.setText("Temperatura");

        lblUmidade.setText("Umidade");

        lblUmidadeValor.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblUmidadeValor.setText("Umidade");

        lblPrecipitacao.setText("Precipitação");

        lblPrecipitacaoValor.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblPrecipitacaoValor.setText("Precipitação");

        btnIniciarParar.setText("Iniciar");
        btnIniciarParar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIniciarPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTemperatura)
                            .addComponent(lblUmidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecipitacao, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUmidadeValor)
                            .addComponent(lblTemperaturaValor)
                            .addComponent(lblPrecipitacaoValor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIniciarParar)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTemperatura)
                .addGap(18, 18, 18)
                .addComponent(lblTemperaturaValor)
                .addGap(41, 41, 41)
                .addComponent(lblUmidade)
                .addGap(18, 18, 18)
                .addComponent(lblUmidadeValor)
                .addGap(49, 49, 49)
                .addComponent(lblPrecipitacao)
                .addGap(18, 18, 18)
                .addComponent(lblPrecipitacaoValor)
                .addGap(61, 61, 61)
                .addComponent(btnIniciarParar)
                .addGap(55, 55, 55))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarPararActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnIniciarPararActionPerformed
    {//GEN-HEADEREND:event_btnIniciarPararActionPerformed
        if (Estaticos.coletaSerial)
        {
            Estaticos.coletaSerial = false;
            btnIniciarParar.setText("Iniciar");
        }
        else
        {
            Estaticos.coletaSerial = true;
            Serial serial = new Serial();
            Thread s1 = new Thread(serial);
            s1.start();
            btnIniciarParar.setText("Parar");
        }
    }//GEN-LAST:event_btnIniciarPararActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Estaticos.coletaSerial = false;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarParar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblPrecipitacao;
    private javax.swing.JLabel lblPrecipitacaoValor;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblTemperaturaValor;
    private javax.swing.JLabel lblUmidade;
    private javax.swing.JLabel lblUmidadeValor;
    // End of variables declaration//GEN-END:variables
}
